DATA:
  data_root: E:\2021CVPR\dataset\cityscapes\cityscapes
  rain_data_root: E:\2021CVPR\dataset\cityscapes\rain\rain_fuse_level5
  train_list: E:\2021CVPR\dataset\cityscapes\list\cityscapes\fine_train.txt
  val_list: E:\2021CVPR\dataset\cityscapes\list\cityscapes\fine_val.txt
  classes: 19

TRAIN:
  arch: iterative_derain_seg
  derain_arch: unet
  seg_arch: bisenetr18
  num_steps: 3
  num_fusion_block: 3
  feed_back: False
  conv_block_num_features: 64
  sync_bn: True  # adopt syncbn or not
  train_h: 500
  train_w: 500
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  derain_loss_type: mse
  derain_loss_weight: 1
  seg_loss_type: ce
  seg_loss_weight: 1
  train_gpu: [0, 1, 2, 3]
  workers: 16  # data loader workers
  batch_size: 8  # batch size for training
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.00001
  epochs: 150
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0
  manual_seed:
  print_freq: 10
  save_freq: 1
  save_path: exp/cityscapes/iterative_unet_bisenetr18/model_lr1e4
  pretrained: True
  derain_pretrained_path: initmodel/derainunet_pretrain_rainstreak_multisupervision_400epoch.pth
  seg_pretrained_path: initmodel/cityscapes-bisenet-R18.pth
  fix_bn: False
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test_list: E:\2021CVPR\dataset\cityscapes\list\cityscapes\fine_val.txt
  split: val  # split in [train, val and test]
  base_size: 2048  # based size for scaling
  test_h: 500
  test_w: 500
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  save_all: False # save all step image
  model_path: exp/cityscapes/iterative_unet_bisenetr18/model_lr1e4/train_epoch_150.pth  # evaluation model path
  save_folder: exp/cityscapes/iterative_unet_bisenetr18/result/temp/epoch_150/val/ss  # results save folder
  colors_path: E:\2021CVPR\dataset\cityscapes\cityscapes_colors.txt  # path of dataset colors
  names_path: E:\2021CVPR\dataset\cityscapes\cityscapes_names.txt  # path of dataset category names
